### ISSUE TITLE
하우시스 제품 카테고리 기획전 지정번호

### ISSUE THREAD

**Issue by dnqls9875** [dnqls9875/front-end-test#2]

**Comment by dnqls2446** [comment]
23A0001 - 인테리어필름
23A0001-01 ->솔리드
23A0001-01-1 ->솔리드
23A0001-01-2 ->미스티
23A0001-01-3 ->듀얼

**Comment by dnqls9875** [comment]
[참고 기획전]
https://ginger-roundworm-cbe.notion.site/13c352094a774660bf4eb0e6799e4140?pvs=4
